### ISSUE TITLE
Runutime Control Display bug

### ISSUE THREAD

**Issue by zengxiaolei** [FlexBE/flexbe_app#47] opened 2019-12-13 06:48 UTC
What I have done is as follows:
 1. Use flexbe_app to run behavior_1
 2. After bahavior_1 is completed, keep flexbe_app opening, but  run behavior_2 by calling action (http://wiki.ros.org/flexbe/Tutorials/Running%20Behaviors%20Without%20Operator).
3. After behavior_2 is completed, run behavior_1 again by flexbe_app. Behavior works, but no runtime control display in the app. As shown by Fig. 1, on-board status is running and  initialization is done, which is really done. Since the display is empty, I cannot continue the next state since a high-level outcome is to be verified as shown in Fg. 2.

![image](https://user-images.githubusercontent.com/34747839/70774622-c505d000-1db5-11ea-9c77-6c53fb6f036b.png)
Fig. 1

![image](https://user-images.githubusercontent.com/34747839/70774791-df3fae00-1db5-11ea-8855-b6acc50ef4c4.png)
Fig. 2

I tried to stop Execution and restart behavior for many times, but problem remains.

**Comment by pschillinger** [comment] 2019-12-13 14:33
Thanks for reporting, I can reproduce this bug and will look into it.

**Comment by pschillinger** [comment] 2019-12-13 16:14
It turned out that the FlexBE App worked as intended, but the issue was caused by flexbe_mirror due to improper release of its thread lock. Consequently, it did not send any behavior updates to the App afterwards.

I fixed it with the above commit.

**Comment by zengxiaolei** [comment] 2019-12-18 05:17
It works!

**Comment by pschillinger** [comment] 2020-02-01 16:37
Fixed in flexbe_behavior_engine version 1.2.3

**Closed by pschillinger** 2020-02-01 16:37 UTC
