### ISSUE TITLE
Behavior parameter's default value is not validating

### ISSUE THREAD

**Issue by alireza-hosseini** [FlexBE/flexbe_app#6] opened 2017-05-26 13:21 UTC
Another issue about behavior parameter is that you can set any default value regardless of whether it is in the MIN and MAX bounds or not.

**Comment by pschillinger** [comment] 2017-06-06 03:49
Can you provide additional details or give an example where this fails? I am not able to reproduce this issue.

**Comment by pschillinger** [comment] 2017-09-30 10:29
Able to replicate: For float values, only the int conversion is used for comparison. Will be fixed soon.

**Closed** 2017-09-30 18:02 UTC
